name: velog 최신 글

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://v2.velog.io/rss/prettylee620"
          max_post_count: 5
          template: "$newline- [$title]($url) <sub>$date</sub>"
          date_format: "yyyy.mm.dd"
          commit_message: "velog 최신 글 갱신"
